[mode.main.binding]

# Layout
ctrl-slash = 'layout tiles horizontal vertical'
ctrl-comma = 'layout accordion horizontal vertical'

# Focus
ctrl-h = 'focus left'
ctrl-j = 'focus down'
ctrl-k = 'focus up'
ctrl-l = 'focus right'

# Move
ctrl-shift-h = 'move left'
ctrl-shift-j = 'move down'
ctrl-shift-k = 'move up'
ctrl-shift-l = 'move right'

# Resize
ctrl-shift-minus = 'resize smart -50'
ctrl-shift-equal = 'resize smart +50'

# Workspaces
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'
ctrl-b = 'workspace B'
ctrl-f = 'workspace F'
ctrl-e = 'workspace E'
ctrl-m = 'workspace M'
ctrl-n = 'workspace N'
ctrl-s = 'workspace S'
ctrl-t = 'workspace T'
ctrl-z = 'workspace Z'
ctrl-v = 'workspace V'

# Move to workspace
ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-6 = 'move-node-to-workspace 6'
ctrl-shift-7 = 'move-node-to-workspace 7'
ctrl-shift-8 = 'move-node-to-workspace 8'
ctrl-shift-9 = 'move-node-to-workspace 9'
ctrl-shift-b = 'move-node-to-workspace B'
ctrl-shift-t = 'move-node-to-workspace T'
ctrl-shift-s = 'move-node-to-workspace S'
ctrl-shift-m = 'move-node-to-workspace M'
ctrl-shift-f = 'move-node-to-workspace F'
ctrl-shift-e = 'move-node-to-workspace E'
ctrl-shift-n = 'move-node-to-workspace N'
ctrl-shift-z = 'move-node-to-workspace Z'
ctrl-shift-v = 'move-node-to-workspace V'

# Workspace back and forth
ctrl-tab = 'workspace-back-and-forth'
ctrl-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Service mode
ctrl-shift-semicolon = 'mode service'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = 'com.brave.Browser'
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = "move-node-to-workspace S"

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = "move-node-to-workspace M"

[[on-window-detected]]
if.app-id = 'notion.id'
run = "move-node-to-workspace N"

[[on-window-detected]]
if.app-id = 'com.edisonmail.edisonmail'
run = "move-node-to-workspace E"

[[on-window-detected]]
if.app-id = 'dev.zed.Zed'
run = "move-node-to-workspace Z"

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = "move-node-to-workspace F"

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij.ce'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = 'com.tinyapp.TablePlus'
run = "move-node-to-workspace 5"

[[on-window-detected]]
if.app-id = 'org.whispersystems.signal-desktop'
run = "move-node-to-workspace 6"

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = "move-node-to-workspace V"

[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = "move-node-to-workspace 1"